// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ct-zh/englishLearn/config"
	"github.com/ct-zh/englishLearn/internal/cli"
	"github.com/ct-zh/englishLearn/internal/dao"
	"github.com/ct-zh/englishLearn/internal/logic/sections"
)

// Injectors from wire.go:

// wireApp 使用Wire进行依赖注入，构建完整的应用
func wireApp() (*cli.App, error) {
	configConfig := config.ProvideConfig()
	daoFactory := dao.ProvideDAOFactory(configConfig)
	sectionDAOInterface := dao.ProvideSectionDAO(daoFactory)
	service := sections.ProvideService(sectionDAOInterface)
	app := cli.ProvideApp(service)
	return app, nil
}
